### ISSUE TITLE
Encoding Gauss facts

### ISSUE THREAD

**Issue by tchakravarty** [eddelbuettel/gaussfacts#1]
@eddelbuettel Dirk, thanks for the amazing package. However, there appear to be encoding issues. Not sure whether you or me.

![gaussfact_encoding](https://cloud.githubusercontent.com/assets/2289192/16943396/3908255a-4db9-11e6-92ec-6db888c93c66.PNG)

Pls help.

**Comment by eddelbuettel** [comment]
Yes, that is something we should fix, and I see in the sibling package [rmsfact](https://github.com/eddelbuettel/rmsfact) that I used [a line in DESCRIPTION](https://github.com/eddelbuettel/rmsfact/blob/master/DESCRIPTION#L13) to specify UTF-8.

Do you have tools locally to build / install a modified R package?  Else I can prepare one for you.  Might be best to test this on your box first.

**Comment by eddelbuettel** [comment]
So I just added the encoding in [this new branch](https://github.com/eddelbuettel/gaussfacts/tree/bugfix/encoding). If you know how to fetch that and test, great.  If not, let me know here and I can email you a tarball (or zipfile).  Let me know if you're Windows and where I should send it to.  You can email me too rather than leaving the address here.

With this, it now works fine for me:

``` r
R> gaussfact(197)             # it now supports an optional index argument
Gauss can both pet and not pet Schrödinger's cat at the same time. 
R> gaussfact(52)
Only Gauss knows whether Schrödinger's cat is dead or alive. 
R> 
```

**Comment by tchakravarty** [comment]
@eddelbuettel Still does not work on my Windows machine. 

I did: 

``` r
devtools::install_github("eddelbuettel/gaussfacts", ref = "bugfix/encoding")
gaussfacts::gaussfact(52)
```

Output is the same as above. I opened the `DESCRIPTION` file and it now has the `Encoding: UTF-8` line. By the way, this version of the code works on my Ubuntu machine, although I have not tested whether it _does not_ work with the old version.

**Comment by eddelbuettel** [comment]
Ok, need to backtrack then and figure this out.  I think there is something in Writing R Extensions related to encodings, and data files, using fortunes as an example.

**Comment by eddelbuettel** [comment]
New idea.  Can you edit the file `R/gaussfacts.R` and alter the data reading line 7 to

``` r
    data <- read.csv(filename, stringsAsFactors=FALSE, encoding="UTF-8") 
```

to make the encoding explicit?

**Comment by tchakravarty** [comment]
@eddelbuettel I made the change that you suggested, and the output of: 

``` r
cat(unique(replicate(1000, gaussfact())), sep = "\n")
```

[looks okay to me](https://gist.github.com/tchakravarty/fd3fec612b588886bbd9bbeb2cb2f1bd). Haven't gone through it in great detail though.  If your inspection does not locate a problem, let me know and I will send you a PR.

**Comment by eddelbuettel** [comment]
Great!  I'll just make the change here then.  

I already had a branch with some other small changes that accumulated.
